### ISSUE TITLE
Can't use the WMA GUI - issue with opening zenity

### ISSUE THREAD

**Issue by sabashahab** [TIGRLab/admin#776]
I'm using Cajal using Laura's account. I can't use the module system. I can't use the whitematteranalysis GUI either.

When I open the terminal, I see this:

bash: /quarantine/Modules/default/init/bash: No such file or directory
bash: /quarantine/Modules/3.2.10/bin/modulecmd: No such file or directory
bash: /quarantine/fsl/4.1.9/x86_64/etc/fslconf/fsl.sh: No such file or directory

This is the error message I get when I type "zenity" in the terminal.

** (zenity:25789): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-CAcZCzgCO3: Connection refused

**Comment by josephdviviano** [comment]
Is this true on multiple machines?

**Comment by lstefanik** [comment]
I also get the same errors on Crick.

**Comment by DESm1th** [comment]
Hey guys,

I seem to have fixed the unrelated issue with wma_applyToSubject.sh throwing errors when run from the GUI. 

With regard to the "Couldn't connect to accessibility bus" errors, those don't seem to be causing the issues with opening the GUI. They're a known issue with Ubuntu and certain GUIs and they can be silenced by adding "export NO_AT_BRIDGE=1" to the end of the .bashrc file.

There was also a minor bug in Final_GUI.sh that was causing "./Final_GUI.sh: line 551: //QCReportResult.txt: Permission denied" messages when tractography was not being run. I've fixed this and left a note in a comment in case my fix ever causes an issue (it shouldnt).

@lstefanik - I don't think my change will have fixed the problem with the window not opening on Crick, but I can take a look at that with you next time you're free. For now the GUI should work on davinci.

**Comment by lstefanik** [comment]
Hi all,

Thanks for fixing the error message below Dawn regarding the wma_applyToSubject.sh.  The good news is that I do not see that error anymore- however the bad news is I still cannot run the clustering step as the accessibility bus error seems to be preventing anything from running (tried on Crick and Davinci this morning).  I have a presentation on Monday and would really like if we could figure this error out asap so I can re-run some SNF analyses with the new DTI data.

Thanks in advance, Laura

Laura Stefanik
MSc Student- Institute of Medical Science
Kimel Family Translational Imaging-Genetics Research Lab
Research Imaging Centre
Campbell Family Mental Health Research Institute
Centre for Addiction and Mental Health, Toronto, Canada

________________________________________

**Comment by lstefanik** [comment]
Update - at Tom's suggestion I added export NO_AT_Bridge=1 before running the script and that got rid of the zenity errors but still did not solve my problem that it will not cluster...

**Comment by josephdviviano** [comment]
It seems like there are multiple issues here.

@sabashahab : those lines should be `/opt/quarantine`. Do you need to update your `.bashrc`?

Otherwise I'm going to need someone to walk me through the analysis, because I'm not familiar with the software and can't replicate the bug on my own.

Come grab me if you want to show me.

**Comment by lstefanik** [comment]
This has been temporarily fixed.

**Comment by DESm1th** [comment]
Issue seems to be resolved, closing this unless anything new pops up.
