### ISSUE TITLE
Set up MATLAB license server

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/admin#93]

**Comment by josephdviviano** [comment]
Hey David,

What's the status on this? r2013 looks like it is set to expire in 5 days:

    ----------------------------------------------------
	Your MATLAB license will expire in 05 days.
	Please contact your system administrator or
	MathWorks to renew this license.
    ----------------------------------------------------

**Comment by djrotenberg** [comment]
Hi Joe,

Something appears to be wrong with the license server. The new licenses were purchased very recently and should not be expiring until next year. I'll look into this now. 

David

**Comment by djrotenberg** [comment]
Hi Guys,

Following: http://www.mathworks.com/matlabcentral/answers/97558-why-do-i-get-license-manager-error-97

(i.e. removing the lockMLM file and the lm_TMW files from /var/tmp). Then restarting the license sever located at :/opt/quarantine/matlab/matlab_concurrent_all/license_manager/build/etc as follows:

./LICENSE_MANAGER.sh start

resolved this issue on my end. Let me know if anyone is still experiencing issues. 

David

**Comment by josephdviviano** [comment]
Hi David, thanks for looking into this so quickly. I'm still getting the warning however.

**Comment by djrotenberg** [comment]
Hi Joe,

OK. Which machine are you attempting this from? I suspect this has to do with the binary that is being sourced. Are you loading the module(s) 'matlab/R2013b_concurrent' (R2012, R2013 and R2014) are working on davinci and mansfield. 

David

**Comment by josephdviviano** [comment]
I see, it was my error, I wasn't sourcing _concurrent.

Do we need those non-concurrent ones any longer? If not I can remove them.

Thanks,

**Comment by djrotenberg** [comment]
Not a problem. The license server itself was having difficultly, so I am glad you caught this! I would suggest that we remove the module files, but not the installs themselves. This way users won't get the wrong binaries, however the previous installs may be useful in the future. What do you two think?

**Comment by josephdviviano** [comment]
I agree. I'll just mv the module files to module.disabled. Thanks for your help with this!!

**Comment by josephdviviano** [comment]
I removed the links ... I just realized renaming wouldn't work for us.
